### ISSUE TITLE
Implementar autentificacion en github

### ISSUE THREAD

**Issue by dba0010** [dba0010/Activiti-Api#10]
Implementar la autentificacion en github para aumentar el rate limit de llamadas a la api de github y mejorar la experiencia con aplicación final

**Comment by cgiohidalgo** [comment]
Hola, estoy intentando desarrollar un prototipo donde  consuma el servicio del API, haciendo uso de  search por repos, traer todos los datos en una consulta, guardarlos en JSON y luego consumir desde este . pero no he logrado hacer esta parte (search por repos y mostrarlos en pantalla). Si pueden darme alguna idea se lo agradecería.

**Comment by dba0010** [comment]
Hola, si echas un vistazo al proyecto puedes ver como uso la biblioteca GitHub Java API (org.eclipse.egit.github.core) para realizar las búsquedas en el API, la misma biblioteca es la que te realiza la búsqueda y te devuelve un List de lo que desees buscar, repositorios, issues, commits.
si observas la clase FachadaConexionGiHub puedes ver los métodos donde están implementadas las búsquedas y la conexión a la API. Espero que te sirva.
